#!/bin/bash

LPAGGREG=/apps/CEPBATOOLS/lpaggreg/default/default

module load GCC
script=$(readlink -f "$0")
scriptpath=$(dirname "$script")
srcpath=$scriptpath/../..
versionpath=$srcpath/../..
cd $versionpath
version=${PWD##*/}
dest=$versionpath/default
mkdir -p $dest
cd $srcpath
make distclean
qmake "CONFIG+=GLOBAL_VAR" "PREFIX=$dest" "LPAGGREG_PATH=$LPAGGREG"
make
make install
path=$versionpath/..
if [ -d $path/default ]
then
  rm $path/default
fi
ln -s $path/$version $path/default
