#!/bin/bash

#   RRI - Relevant Routine Identifier
#   Copyright (C) 2016  Damien Dosimont
#
#   This file is part of RRI.
#
#   RRI is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

basedir=$(dirname $0)
rscript=$basedir/rri-folding.R
width=6
height=1
dpi=300
clean="false"

usage_fct(){
  echo "Usage : $0 [options] <folding-directory>"
  echo "Options:"
  echo "-h --help: Print help"
  echo "-c --clean: Remove all the generated pdf"
  echo "-s --size [w] [h]: Set pdf outputs width and height in inch (default: $width $height)"
  echo "-d --dpi [n]: Set pdf outputs dpi (default: $dpi)"
  exit 2
}

if [ -f "rri-folding.R" ]
then
  rscript=rri.R
elif [[ ! -f "$rscript" ]]
then
  if [[ -f "${RRI_PATH}/rri-folding.R" ]]
  then
    rscript=${RRI_PATH}/rri-folding.R
  else
    echo "The required R script rri-folding.R has not been found. Set the environment variable RRI_PATH to the directory that contains it. Leaving..."
    exit 1
  fi
fi
#No arguments
if [ $# -eq 0 ]
then
  usage_fct
fi
#Test arguments
while [ $# -gt 1 ]
do
  if [ $1 = "-h" ] || [ $1 = "--help" ]
  then
    usage_fct
    exit 0
  elif [ $1 = "-s" ] || [ $1 = "--size" ]
  then
    shift
    width=$1
    shift
    height=$1
  elif [ $1 = "-d" ] || [ $1 = "--dpi" ]
  then
    shift
    dpi=$1
  fi
  shift
done
if [ ! -d $1 ]
then
  echo "$1 is not a valid directory"
  usage_fct
  exit 1
fi
input_dir=$1
rm -fr $input_dir/parts/
mkdir -p $input_dir/parts
for region in `sed -n '2,$p' $input_dir/*.callerdata.regions | cut -d';' -f1`
do
  sub_dir=$input_dir/parts/$region
  mkdir -p $sub_dir
  for counter in `cat $input_dir/*.fused.counters`
  do
    if [ -f $input_dir/*$region.*$counter.gnuplot ]
    then
      ts=( `grep "set obj rect" $input_dir/*$region.*$counter.gnuplot | grep -o "[0-9].[0-9][0-9][0-9]\*FACTOR" | grep -o "[0-9].[0-9][0-9][0-9]"` )
      func=( `grep "set obj rect" $input_dir/*$region.*$counter.gnuplot | grep -o "# Routine:.*" | sed -e 's/#\ Routine: //g' | cut -d' ' -f1` )
      e=`expr ${#func[@]} - 1` 
      for i in `seq 0 $e`
      do
        i1=`expr $i \\* 2`
        i2=`expr $i1 + 1`
        echo ${ts[$i1]}, ${ts[$i2]}, ${func[$i]} >> $sub_dir/parts.csv
      done
      break
    fi
  done
  R --slave --vanilla --args $input_dir $sub_dir $region $sub_dir $width $height $dpi < $rscript
done
