#ifndef PROFILING_CONSTANTS_H
#define PROFILING_CONSTANTS_H

#endif // PROFILING_CONSTANTS_H

#define CSV_STATS_REGION 0
#define CSV_STATS_GROUP 1
#define CSV_STATS_TOTAL_INS_NUMBER 2
#define CSV_STATS_TOTAL_SAMPLE_NUMBER 3
#define CSV_STATS_TOTAL_MEDIAN 4
#define CSV_STATS_TOTAL_MAD 5
#define CSV_STATS_SIGMA_FACTOR 6
#define CSV_STATS_SELECTION_INTERVAL_MIN 7
#define CSV_STATS_SELECTION_INTERVAL_MAX 8
#define CSV_STATS_SELECTED_INS_NUMBER 9
#define CSV_STATS_SELECTED_INS_PROPORTION 10
#define CSV_STATS_SELECTED_INS_MEDIAN 11
#define CSV_STATS_SELECTED_INS_MAD 12

#define CSV_SLOPE_REGION 0
#define CSV_SLOPE_GROUP 1
#define CSV_SLOPE_COUNTER 2
#define CSV_SLOPE_TS 3
#define CSV_SLOPE_VALUE 4
#define CSV_SLOPE_UNKNOWN 5

#define CSV_SLOPE_SIZE CSV_SLOPE_UNKNOWN+1


#define RETURN_OK 0
#define RETURN_ERR_GROUP 1
#define RETURN_ERR_CSVLINESIZE 2

#define SEP ";"
#define SEP2 ":"

