#ifndef RRIPROFILING_GLOBAL_H
#define RRIPROFILING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RRIPROFILING_LIBRARY)
#  define RRIPROFILINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RRIPROFILINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RRIPROFILING_GLOBAL_H
