#!/bin/bash

source settings

script=$(readlink -f "$0")
scriptpath=$(dirname "$script")
apppath=$scriptpath/../..
version=`$scriptpath/version`
target=$APPDIR/$APP/$version/src
cmd=`ssh $SSHTARGET "rm -fr $target && mkdir -p $target"`
cd $apppath
repo=${PWD##*/}
cd $scriptpath
scp -r $apppath/../$repo $SSHTARGET:$target/
cmd=`ssh $SSHTARGET "cd $target/$repo/.packaging/minotauro/ && ./deploy"`
if [ -f $scriptpath/module ]
then
  module=$MODULEDIR/$MODULE
  scp module $SSHTARGET:$module/$version
  cmd=`ssh $SSHTARGET "rm -f $module/latest && ln -s $module/$version $module/latest"`
fi
