#!/bin/bash

config=$1

script=$(readlink -f "$0")
scriptpath=$(dirname "$script")
configpath=$scriptpath/$config
if [ ! -d $configpath ]
then
echo "$config configutation not found"
exit 1
fi
apppath=$scriptpath/..
version=`$scriptpath/version`
source $configpath/settings
target=$APPDIR/$APP/$version/src
cmd=`ssh $SSHTARGET "rm -fr $target && mkdir -p $target"`
cd $apppath
repo=${PWD##*/}
make distclean
cd $scriptpath
scp -r $apppath/../$repo $SSHTARGET:$target/
cmd=`ssh $SSHTARGET "cd $target/$repo/.packaging/$config && ./deploy"`
if [ -f $configpath/module ]
then
  module=$MODULEDIR/$MODULE
  cp $configpath/module module.temp
  sed -i "s/X.X.X/$version/g" module.temp
  scp module.temp $SSHTARGET:$module/$version
  cmd=`ssh $SSHTARGET "rm -f $module/latest && ln -s $module/$version $module/latest"`
  rm module.temp
fi
